# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: CI=false npm run build --if-present
    - run: pwd
    - run: ls
    #- run: git config --global user.email hassanmahmoud607@gmai.com
    #- run: git config --global user.name hassan510-cmd
    #- run: git add build 
    #- run: git commit -m "add new build"
    #- run: git push 
    - run: git clone "https://github.com/hassan510-cmd/build_static"
    - run: cd build_static 
    - run: cp -R ../build/ .
    - run: git config --global user.email hassanmahmoud607@gmai.com
    - run: git config --global user.name hassan510-cmd
    - run: git add * 
    - run: git commit -m "from dev repo"
    - run: git push 
